- src/app.js
- src/config.json
*adding allocate associate release (address) and describe an instance methods
*fixing tag bug
> KG-464   EC2 Plugin - Add methods

- src/config.json
Hello Amit. Please consider these changes. Thanks.
> updated defaults and text to be more clear and correct.

- payload-functions.js
[**KP-621 in Jira**](https://kaholo.atlassian.net/browse/KP-621)
> KP-621 [AWS EC2] method Add Security Group Rules IP Protocol "All" should not require ports

- app.js
- config.json
- consts.json
- helpers.js
- payload-functions.js
[**KP-586 in Jira**](https://kaholo.atlassian.net/browse/KP-586)
> KP-586 [AWS EC2] method Describe Instances - broken in several ways

- .eslintrc.js
- autocomplete.js
- helpers.js
[**KP-606 in Jira**](https://kaholo.atlassian.net/browse/KP-606)
> KP-606 [AWS EC2] subnet autocomplete with subnet Name also

- app.js
- config.json
[**KP-617 in Jira**](https://kaholo.atlassian.net/browse/KP-617)
> KP-617 [AWS EC2] give Method Stop Instances a way to wait for them to stop

- config.json
https://kaholo.atlassian.net/browse/KP-580
> [KP-580] Method create instance security groups not working

- app.js
- config.json
- payload-functions.js
https://kaholo.atlassian.net/browse/KP-583
> [KP-583] Allow tagging for Elastic IP addresses

- config.json
- payload-functions.js
[**KP-585 in Jira**](https://kaholo.atlassian.net/browse/KP-585)
> KP-585 [AWS EC2] method Associate An Address - remove parameters Public IP and Allow Reassociation

- config.json
- payload-functions.js
[**KP-582 in Jira**](https://kaholo.atlassian.net/browse/KP-582)
> KP-582 [AWS EC2] Remove Domain Type Parameter

- config.json
[**KP-592 in Jira**](https://kaholo.atlassian.net/browse/KP-592)
> KP-592 [AWS EC2] Remove parameters Create Route Table and Create Security Group from method Create VPC

- app.js
- autocomplete.js
- package.json
- payload-functions.js
[**KP-821 in Jira**](https://kaholo.atlassian.net/browse/KP-821)
> KP-821 [Several Plugins] Replace dependency on Github in package.json with the NPM package

- app.js
- helpers.js
[**KP-1198 in Jira**](https://kaholo.atlassian.net/browse/KP-1198)
> KP-1198 ([AWS EC2] method Modify Instance Attribute unusable)

- autocomplete.js
[**KP-1197 in Jira**](https://kaholo.atlassian.net/browse/KP-1197)
> KP-1197 ([AWS EC2] method Modify Instance Type parameter Instance Type - autocomplete resets to empty instance type parameter)

- app.js
- payload-functions.js
[**KP-1199 in Jira**](https://kaholo.atlassian.net/browse/KP-1199)
> KP-1199 ([AWS EC2] method Create VPC parameter Tags - Unexpected key 'Tags' found in params)

- config.json
Added:
* [**KP-1124**](https://kaholo.atlassian.net/browse/KP-1124) Accounts feature
Fixed:
* [**KP-1197**](https://kaholo.atlassian.net/browse/KP-1197) Broken autocompletes
* [**KP-1198**](https://kaholo.atlassian.net/browse/KP-1198) _Modify Instance Attribute_ method
* [**KP-1199**](https://kaholo.atlassian.net/browse/KP-1199) _Create VPC_ method
> Release v3.0.0

- config.json
- package-lock.json
[**KP-1215 in Jira**](https://kaholo.atlassian.net/browse/KP-1215)
> KP-1215 (Prepare multiple plugins to publish in the Artifactory)

- app.js
[**KP-1231 in Jira**](https://kaholo.atlassian.net/browse/KP-1231)
> KP-1231 ([AWS EC2] method Create Route Table - Error: Missing required key 'RouteTableId' in params)

- autocomplete.js
[**KP-1214 in Jira**](https://kaholo.atlassian.net/browse/KP-1214)
> KP-1214 ([AWS EC2] - VPC selection does not narrow subnet Autocomplete selection)

- config.json
- package-lock.json
- package.json
- payload-functions.js
[**KP-1257 in Jira**](https://kaholo.atlassian.net/browse/KP-1257)
> KP-1257 ([AWS EC2] method Create Route Table parameter Tags - doesn't allow tags without values)

- app.js
[**KP-1273 in Jira**](https://kaholo.atlassian.net/browse/KP-1273)
> KP-1273 ([AWS EC2] method Create Tags returns empty Final Result)

- package-lock.json
- package.json
[**KP-1288 in Jira**](https://kaholo.atlassian.net/browse/KP-1288)
> KP-1288 ([AWS EC2] Update `aws-plugin-library` reference)

- config.json
- minor improvements in config.json only
> [KP-1334] Release v3.2.1

- app.js
- autocomplete.js
- helpers.js
- package-lock.json
- package.json
[**KP-1333 in Jira**](https://kaholo.atlassian.net/browse/KP-1333)
> KP-1333 ([AWS EC2] Big Update)

- INSTALL.md
- app.js
- config.json
- package-lock.json
- package.json
- payload-functions.js
-   Update INSTALL.md
-   Many improvements to config.json
-   Removed deprecated PublicIp param
-   Removed wrapping of results in property of method name
-   Fix for create subnet with NAT gateway (subnetId + SubnetId)
> [KP-1380] Release Prep

- app.js
- package-lock.json
[**KP-1384 in Jira**](https://kaholo.atlassian.net/browse/KP-1384)
> KP-1384 ([AWS EC2] function createSubnetWorkflow - both SubnetID and subnetID requried?)

- config.json
- package-lock.json
- package.json
- Upgrade to aws-sdk v3
- Security vulnerability fixes
- Many minor bug fixes
- Many minor cosmetic and usability fixes
- Updated documentation
> [KP-1386] Release v3.3.0
